{{ if eq .Values.ingressController "nginx" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: genesis-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/auth-url: "http://genesis.{{ .Release.Namespace }}.svc.cluster.local:3000/api/socket-auth/"
spec:
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: genesis
                port:
                  number: 3000
          - path: "/socket.io"
            pathType: ImplementationSpecific
            backend:
              service:
                name: genesis
                port:
                  number: 8000
{{ end }}