name: Lint cedar policies
on:
  push:
jobs:
  lint:
    name: Lint cedar policies
    runs-on: X64
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run the lint target
        shell: bash
        run: |
          devbox run make lint-cedar
